export const Company = [
	'Activision',
	'Al Alamiah',
	'Anma',
	'ASCII',
	'Bothtec',
	'The Bytebusters',
	'Casio',
	'Compile',
	'dB-SOFT',
	'ENIX',
	'German Gomez Herrera',
	'Hudson Soft',
	'Hudson Soft / Japanese Softbank',
	'Infinite',
	'Karoshi Corporation',
	'Kai Magazine',
	'Konami',
	'Mass Tael',
	'Microcabin',
	'NAMCO',
	'Nippon Columbia / Colpax / Universal',
	'Pack-In-Video',
	'Parallax',
	'Paxanga Soft',
	'Pony Canyon',
	'Sega',
	'Sony',
	'TAITO',
	'T&ESOFT',
	'Telenet Japan',
	'ZAP',
	'Zemina'
];
