export const Genre = [
    'Unknown',
    'Action',
    'Adult',
    'Adventure (All)',
    'Adventure | Point and Click',
    'Adventure | Text and Gfx',
    'Adventure | Text only',
    'Arcade',
    'Board Games',
    'Break-out',
    'Card Games',
    'Communication',
    'Compiler',
    'Database',
    'DTP',
    'Educational',
    'Fighting',
    'Financial',
    'Gambling / Fruit Machine',
    'Graphics',
    'Miscellaneous',
    'Office',
    'Operating System',
    'Parody',
    'Pinball',
    'Platform',
    'Puzzle',
    'Quiz',
    'Racing',
    'Remake',
    'RPG',
    'Shoot-\'em-up (All)',
    'Shoot-\'em-up | First-person shooter',
    'Shoot-\'em-up | Horizontal',
    'Shoot-\'em-up | Isometric',
    'Shoot-\'em-up | Multi-directional',
    'Shoot-\'em-up | Vertical',
    'Simulation',
    'Sound',
    'Sports Games',
    'Sport Management',
    'Spreadsheet',
    'Strategy',
    'Tool',
    'Variety',
    'War Games',
    'Word Processor',
    'Maze',
    'Pong',
    'Beat-\'em-up',
    'Dexterity',
    'Dungeon',
];
